CREATE TABLE IF NOT EXISTS `users`
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      varchar(255) NOT NULL UNIQUE,
    login      varchar(50) NOT NULL UNIQUE,
    name       varchar(50) NOT NULL,
    birthday   date NOT NULL
);

CREATE TABLE IF NOT EXISTS `film`
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         varchar(100),
    description  text NOT NULL,
    release_date date NOT NULL,
    duration     int NOT NULL,
    mpaa_id       int NOT NULL
);
CREATE TABLE IF NOT EXISTS `like`
(
    user_id    INTEGER NOT NULL,
    film_id    INTEGER NOT NULL,
    PRIMARY KEY (user_id, film_id)
);
CREATE TABLE IF NOT EXISTS `friends`
(
    user_id    INTEGER NOT NULL,
    friend_id  INTEGER NOT NULL,
    status     boolean   DEFAULT false,
    PRIMARY KEY (user_id, friend_id)
);
CREATE TABLE IF NOT EXISTS `film_genre`
(
    film_id    INTEGER,
    genre_id   INTEGER,
    PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS `genre`
(
    genre_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       varchar(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS `mpa`
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(10)
);
